### ISSUE TITLE
Define Project

### ISSUE THREAD

**Issue by Elias-Carr** [Elias-Carr/IT115Team2#1]
Let's have our website be called "IT Information." We can use the paragraphs we wrote for Assignment 3 Wiki as subject pages. We'll have a home page and a credits page too

**Comment by heyhaylan** [comment]
Would everyone be open to instead of having a theme that we all adhere to, we each do whatever we'd like for our own page on the website? We'd still have a home page that links to each separate web page. Articles on IT related stuff is a bit ~dry and since the content doesn't matter so much, it might be more motivating for us to add something to the website that is fun to do. What do y'all think? @ElMarcoPollo @davidOrtega18 @Elias-Carr (sorry for the tags, I'm not sure how visible comments are across github yet and want to make sure y'all see this.
