### ISSUE TITLE
Define Pages - Number of Pages and the companies

### ISSUE THREAD

**Issue by ElMarcoPollo** [Elias-Carr/IT115Team2#28]

**Comment by heyhaylan** [comment]
I'm not sure if we need to set a cap on the number of pages, since it will be a good task for people to pick up if they have nothing else to do but I'm curious what everyone else thinks. As far as researching which companies to include, that might be a good task itself - have someone create a list of companies and we can work off that when deciding what to research

**Comment by davidOrtega18** [comment]
I think one per should be fine.
