### ISSUE TITLE
Research Company - Valve

### ISSUE THREAD

**Issue by heyhaylan** [Elias-Carr/IT115Team2#45]
Company name:
Location:
Mission statement:
IT roles:
Glassdoor rating:
Benefits:

Link to jobs/careers page.

**Comment by Elias-Carr** [comment]
Company name: Valve
Location: Bellevue
Mission statement: (No official mission statement)
IT roles:
- Game Development Software Engineer
- Electrical Engineer
- Industrial Designer
- Software Engineer for HW
- Hardware Sourcing and Supply Chain
- Mechanical Engineer
- Steam Database Administrator
Glassdoor rating: https://www.glassdoor.com/Reviews/Valve-Corporation-Reviews-E24849.htm
Benefits:
Valve is somewhat of a secretive company and doesn't list their official benefits on their website. However they are known to be one of the best game design companies to work at that offer a very flexible work schedule and the ability to work on whatever project the employee desires. Because of this, they keep their number of employees low at about 360 at the time of writing. This is incredibly small compared to other large game companies which have employee numbers in the thousands. 
Link to jobs/careers page: https://www.valvesoftware.com/en/
